<!-- JavaScript Errors - Throw and Try to Catch The try statement lets you test a
block of code for errors. The catch statement lets you handle the error. The
throw statement lets you create custom errors. The finally statement lets you
execute code, after try and catch, regardless of the result.

JavaScript Errors - Throw and Try to Catch
The try statement lets you test a block of code for errors.

The catch statement lets you handle the error.

The throw statement lets you create custom errors.

The finally statement lets you execute code, after try and catch, regardless of the result.
 -->

<!DOCTYPE html>
<html>
  <body>
    <h2>JavaScript Error Handling</h2>

    <p>This example demonstrates how to use <b>catch</b> to diplay an error.</p>

    <p id="demo"></p>

    <script>
      try {
        adddlert("Welcome guest!");
      } catch (err) {
        document.getElementById("demo").innerHTML = err.message;
      }
    </script>
  </body>
</html>

<!-- JavaScript try and catch
The try statement allows you to define a block of code to be tested for errors while it is being executed.

The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

The JavaScript statements try and catch come in pairs:

try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
} -->

<!-- The throw Statement
The throw statement allows you to create a custom error.

Technically you can throw an exception (throw an error).

The exception can be a JavaScript String, a Number, a Boolean or an Object:

throw "Too big";    // throw a text
throw 500;          // throw a number -->

<!DOCTYPE html>
<html>
  <body>
    <p>Please input a number between 5 and 10:</p>

    <input id="demo" type="text" />
    <button type="button" onclick="myFunction()">Test Input</button>
    <p id="p01"></p>

    <script>
      function myFunction() {
        var message, x;
        message = document.getElementById("p01");
        message.innerHTML = "";
        x = document.getElementById("demo").value;
        try {
          if (x == "") throw "empty";
          if (isNaN(x)) throw "not a number";
          x = Number(x);
          if (x < 5) throw "too low";
          if (x > 10) throw "too high";
        } catch (err) {
          message.innerHTML = "Input is " + err;
        }
      }
    </script>
  </body>
</html>


<!-- HTML Validation
The code above is just an example.

Modern browsers will often use a combination of JavaScript and built-in HTML validation, using predefined validation rules defined in HTML attributes: -->

<input id="demo" type="number" min="5" max="10" step="1">


<!-- Error Name Values
Six different values can be returned by the error name property:

Error Name	Description
EvalError	An error has occurred in the eval() function
RangeError	A number "out of range" has occurred
ReferenceError	An illegal reference has occurred
SyntaxError	A syntax error has occurred
TypeError	A type error has occurred
URIError	An error in encodeURI() has occurred -->

